# -*- coding: utf-8 -*-
"""Copia de Clase 09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bg4iI1vY51solw8aRLDITQs9VKtK33lz
"""

# !python -m pip install drawdata
!python -m pip install pingouin

from drawdata import draw_scatter

draw_scatter()



from sklearn.linear_model import LinearRegression
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.api as sm
from scipy import stats
import pingouin as pg

mpl.style.use('bmh')

import pandas as pd
pd.set_option('display.max_rows', 10) 
import numpy as np
datos = pd.read_csv("/home/data (1).csv",sep=",")
datos

tipo = 'c'
datos = pd.read_csv("/home/data (1).csv",sep=",")
datos = datos[(datos.z==tipo)]
datos.x
var_x = np.array(datos.x).reshape(-1, 1)
var_y = datos.y
reg = LinearRegression().fit(var_x, var_y)
leyenda = "y = " + str(round(reg.intercept_,2)) + "+" + str(round(reg.coef_[0],2)) + "x"
pred_y = reg.predict(var_x)
fig, ax = plt.subplots()
ax.set_title(leyenda)
ax.set_xlabel('Variable x')
ax.set_ylabel('Variable y')
ax.plot(var_x,pred_y,c='red')
ax.scatter(var_x,var_y)
pg.linear_regression(var_x, var_y)

datos_no_b = pd.read_csv("/Hoja de cálculo sin título - Hoja 1.csv")
var_x = np.array(datos_no_b["Cant de fert"]).reshape(-1, 1)
var_y = datos_no_b.Rendimiento
reg = LinearRegression().fit(var_x, var_y)
leyenda = "y = " + str(round(reg.intercept_,2)) + "+" + str(round(reg.coef_[0],2)) + "x"
pred_y = reg.predict(var_x)
fig, ax = plt.subplots()
ax.set_title(leyenda)
ax.set_xlabel('Variable x')
ax.set_ylabel('Variable y')
ax.plot(var_x,pred_y,c='red')
ax.scatter(var_x,var_y)
pg.linear_regression(var_x, var_y)